name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y graphicsmagick libxss1 build-essential chrpath libssl-dev libxft-dev libfontconfig1 libfontconfig1-dev
          wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
          tar xvjf phantomjs-1.9.8-linux-x86_64.tar.bz2
          sudo mv phantomjs-1.9.8-linux-x86_64 /usr/local/share
          sudo ln -sf /usr/local/share/phantomjs-1.9.8-linux-x86_64/bin/phantomjs /usr/local/bin
          yarn install
      - name: Test with yarn
        run: |
          yarn test
        env:
          CI: true

